name: youtube-summary
on:
  schedule:
    - cron: '0 9 * * *'      # 日本時間 18:00
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_TOKEN:   ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID:   ${{ secrets.NOTION_DB_ID }}
          YT_API_KEY:     ${{ secrets.YT_API_KEY }}
          CHANNEL_IDS:    ${{ secrets.CHANNEL_IDS }}
          TZ:             ${{ secrets.TZ }}

